server:
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.test.com
    tls: true
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

configs:
  params:
    server.insecure: true
