// Code generated by pmctl. DO NOT EDIT.
// To regenerate, run: pmctl gen service

package service

import (
	"go-service-template/helper/cache"
	"go-service-template/helper/toolkit/downloader"
	"go-service-template/helper/toolkit/oncex"
	"go-service-template/internal/config"
	"go-service-template/internal/repository"
)

// ServiceFactoryContext defines the minimal interface needed to create services
type ServiceFactoryContext interface {
	GetConfig() config.Config
	GetDownloader() downloader.Downloader
	GetProductRepo() repository.ProductRepository
	GetCacheClient() cache.Cache
}

// ServiceFactory creates and manages service instances
// Uses lazy initialization with oncex to create services only when needed
type ServiceFactory struct {
	ctx ServiceFactoryContext

	// Lazy-initialized services
	
	productService   oncex.OnceValue[ProductService]
}

// NewServiceFactory creates a new service factory from a context
func NewServiceFactory(ctx ServiceFactoryContext) *ServiceFactory {
	return &ServiceFactory{
		ctx: ctx,
	}
}



// GetProductService returns the ProductService instance (lazy-initialized)
func (f *ServiceFactory) GetProductService() ProductService {
	return f.productService.MustGet(func() ProductService {
		return NewProductService(
			f.ctx.GetProductRepo(),
			f.ctx.GetCacheClient(),
		)
	})
}
